# Generated by Django 3.2.7 on 2021-09-16 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_auto_20210916_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='field_name',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
