# Generated by Django 3.2.7 on 2021-09-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_feature_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='field_name',
        ),
    ]
